### ISSUE TITLE
Gros ajout de réseaux du 23 juillet : des lenteurs à résoudre

### ISSUE THREAD

**Issue by laem** [laem/gtfs#23]
- [ ] Maintenant on doit bosser les lenteurs. Voir https://github.com/laem/cartes/issues/416#issuecomment-2231460146

- [ ] Toulouse ne semble pas marcher dans Motis

**Comment by laem** [comment]
![Sélection_163](https://github.com/user-attachments/assets/1dabb05f-8b66-43ef-be1c-a7a2e6e3b8e5)
![Sélection_164](https://github.com/user-attachments/assets/3fdbd399-8c16-4da4-b507-f305d6e0b303)
![Sélection_165](https://github.com/user-attachments/assets/72d7a546-58ab-4a96-ab78-319bd6253163)
![Sélection_166](https://github.com/user-attachments/assets/9a7269be-1602-49d7-9ba8-9102e00d1504)
![Sélection_167](https://github.com/user-attachments/assets/e85c5507-a63f-4c4f-83c3-6bf1968956b4)

**Comment by Jean-BaptisteC** [comment]
J'ai testé aussi Épinal et Metz, le TEC fonctionne bien
