### ISSUE TITLE
Passer à un serveur dédié 

### ISSUE THREAD

**Issue by laem** [laem/gtfs#24]
Nous utilisons actuellement du Scaleway compute, mais le Elastic meta serait semble-t-il beaucoup moins cher avec notamment 32Go, ce qui nous permettrait de parser france.osm.pbf sur le serveur. 

Ça demande un peu de plomberie, et surtout un engagement mensuel.

**Comment by Aeris1One** [comment]
Est-ce que Motis supporte le découplage de la génération du graphe et son utilisation ?

Je sais qu'OpenTripPlanner permet d'utiliser une machine puissante pour générer le graphe des réseaux puis des machines moins puissantes qui n'y ont accès qu'en lecture-seule et exposent l'API.

Si c'est le cas, on pourrait peut-être faire un système un peu plus avancé : 
- lorsqu'il y a une mise à jour des GTFS on lance une instance Compute qui génère le graphe Motis, l'uploade sur du S3 puis s'éteint (cette machine très puissante, comme actuellement, n'est allumée qu'une à deux heures par jour, et seulement les jours où les GTFS ont changé dans l'idéal)
- ensuite, une autre instance Compute bien moins puissante, qui est allumée en permanence. Lorsqu'elle démarre elle récupère le graphe depuis S3 et expose l'API. Elle est redémarrée chaque nuit après que la première instance ait terminé de construire le graphe.

Avantages : 
- c'est moins cher que d'avoir la machine puissante allumée (et donc facturée) en permanence
- ça réduit énormément le temps d'indisponibilité de Motis la nuit (seule indisponibilité le temps que la petite machine télécharge le nouveau graphe et lance)

Inconvénients : 
- 2 machines à gérer
- Paiement moins prévisible (devient dépendant du temps de compilation du graphe)

**Comment by laem** [comment]
> EDIT: Non, Motis ne semble pas supporter ce fonctionnement.

Ah bon, pourquoi ? Au contraire, j'ai déjà généré en local sur ma machine de 32 go les données nécessaires au routing OSRM et PPR :) Je crois que pour le module Nigiri c'est pareil.

**Comment by laem** [comment]
J'ai commencé à mettre en place un serveur dédié, sur serveur.cartes.app. Et aussi commencé à mettre en place des scripts ansible dans le dossier du même nom, mais c'est un peu de taf que je n'ai pas envie de faire maintenant.

**Comment by laem** [comment]
Je ferme, on reparlera du passage à l'échelle de Motis par la suite.
